#include "levels/arena_pillars/texture_include.inc.c"
#include "levels/arena_pillars/area_1/collision.inc.c"
#include "levels/arena_pillars/area_1/macro.inc.c"
#include "levels/arena_pillars/area_1/spline.inc.c"
#include "levels/arena_pillars/model.inc.c"
