#include "levels/arena_platforms/texture_include.inc.c"
#include "levels/arena_platforms/area_1/collision.inc.c"
#include "levels/arena_platforms/area_1/macro.inc.c"
#include "levels/arena_platforms/area_1/spline.inc.c"
#include "levels/arena_platforms/model.inc.c"
