#include "levels/arena_example/texture_include.inc.c"
#include "levels/arena_example/area_1/collision.inc.c"
#include "levels/arena_example/area_1/macro.inc.c"
#include "levels/arena_example/area_1/spline.inc.c"
#include "levels/arena_example/model.inc.c"
