#include "levels/arena_citadel/texture_include.inc.c"
#include "levels/arena_citadel/area_1/collision.inc.c"
#include "levels/arena_citadel/area_1/macro.inc.c"
#include "levels/arena_citadel/area_1/spline.inc.c"
#include "levels/arena_citadel/model.inc.c"
