extern const GeoLayout arena_example_area_1_geo[];
extern const GeoLayout arena_example_area_1[];
extern const Collision arena_example_area_1_collision[];
extern const MacroObject arena_example_area_1_macro_objs[];
extern Lights1 arena_example_dl_f3dlite_material_001_lights;
extern u8 arena_example_dl_tile_rgba16[];
extern Vtx arena_example_dl_LevelGeo_mesh_layer_1_vtx_0[44];
extern Gfx arena_example_dl_LevelGeo_mesh_layer_1_tri_0[];
extern Gfx mat_arena_example_dl_f3dlite_material_001[];
extern Gfx arena_example_dl_LevelGeo_mesh_layer_1[];
extern Gfx arena_example_dl_material_revert_render_settings[];
