extern const GeoLayout ddd_area_1_geo[];
extern const GeoLayout ddd_area_1[];
extern const Collision ddd_area_1_collision[];
extern const MacroObject ddd_area_1_macro_objs[];
extern u8 ddd_dl_big_bricks_rgba16[];
extern u8 ddd_dl_LevelGeo_001_Bake1_CyclesBake_COMBINED_rgba16[];
extern u8 ddd_dl_tile_rgba16[];
extern u8 ddd_dl_dirt2_rgba16[];
extern u8 ddd_dl_big_bricks_blue_rgba16[];
extern u8 ddd_dl_tile2_rgba16[];
extern Vtx ddd_dl_z_level_mesh_layer_1_vtx_0[995];
extern Gfx ddd_dl_z_level_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_z_level_mesh_layer_1_vtx_1[38];
extern Gfx ddd_dl_z_level_mesh_layer_1_tri_1[];
extern Vtx ddd_dl_z_level_mesh_layer_1_vtx_2[599];
extern Gfx ddd_dl_z_level_mesh_layer_1_tri_2[];
extern Vtx ddd_dl_z_level_mesh_layer_1_vtx_3[999];
extern Gfx ddd_dl_z_level_mesh_layer_1_tri_3[];
extern Vtx ddd_dl_z_level_mesh_layer_1_vtx_4[38];
extern Gfx ddd_dl_z_level_mesh_layer_1_tri_4[];
extern Gfx mat_ddd_dl_Material_003_f3d_006[];
extern Gfx mat_revert_ddd_dl_Material_003_f3d_006[];
extern Gfx mat_ddd_dl_Material_f3d_004[];
extern Gfx mat_revert_ddd_dl_Material_f3d_004[];
extern Gfx mat_ddd_dl_Material_002_f3d_006[];
extern Gfx mat_revert_ddd_dl_Material_002_f3d_006[];
extern Gfx mat_ddd_dl_Material_001_f3d_004[];
extern Gfx mat_revert_ddd_dl_Material_001_f3d_004[];
extern Gfx mat_ddd_dl_Material_004_f3d_006[];
extern Gfx mat_revert_ddd_dl_Material_004_f3d_006[];
extern Gfx ddd_dl_z_level_mesh_layer_1[];
extern Gfx ddd_dl_material_revert_render_settings[];
