#include "levels/arena_spire/texture_include.inc.c"
#include "levels/arena_spire/area_1/collision.inc.c"
#include "levels/arena_spire/area_1/macro.inc.c"
#include "levels/arena_spire/area_1/spline.inc.c"
#include "levels/arena_spire/model.inc.c"
